// packages/lsp-test-client/fixtures/editor-neutral/src/policy/lax/vue/JavaScriptEventHandler.vue
<script setup>
/** @param {PointerEvent} e */
function myClick(e) {
  e.pointerId;
  // @ts-expect-error authored PointerEvent has no such member; lax policy suppresses diagnostics
  return e.__verterMissingPointerMember;
}
</script>

<template><button @pointerdown="myClick">Click</button></template>

// packages/lsp-test-client/fixtures/editor-neutral/src/policy/lax/svelte/JavaScriptEventHandler.svelte
<script>
  let lastPointerId = $state(0);

  /** @param {PointerEvent} e */
  function myClick(e) {
    e.pointerId;
    // @ts-expect-error authored PointerEvent has no such member; lax policy suppresses diagnostics
    lastPointerId = e.__verterMissingPointerMember;
  }
</script>

<button onpointerdown={myClick}>Click</button>
<output>{lastPointerId}</output>
